# Generated by Django 4.2 on 2023-04-25 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='account name')),
            ],
        ),
        migrations.CreateModel(
            name='IndependentIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='independent income name')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='independent income amount')),
                ('date', models.DateField(verbose_name='independent income date')),
            ],
        ),
        migrations.CreateModel(
            name='WageJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='wage job name')),
                ('wage', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='hourly rate')),
                ('pay_interval', models.IntegerField(verbose_name='weeks between paydays')),
                ('pay_weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='weekday of payday')),
            ],
        ),
        migrations.CreateModel(
            name='WageTimesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date worked')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='hours worked')),
                ('wage_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.wagejob')),
            ],
        ),
        migrations.CreateModel(
            name='Paycheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='amount on paycheck')),
                ('is_paid', models.BooleanField(default=False)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entry.account')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='expense amount')),
                ('description', models.CharField(max_length=255, verbose_name='expense description')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entry.account')),
            ],
        ),
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='account balance')),
                ('date_effective', models.DateField(verbose_name='date effective')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.account')),
            ],
        ),
    ]
